### ISSUE TITLE
About input features.

### ISSUE THREAD

**Issue by XuZhengzhuo** [silicx/DLSA#1]
Thanks for your opening work!
 
Some questions are bothering me:

1. How to get the input feature? The feature is extracted by augmented images or not? If so, is the augmentation consistent with the original repo like paco? Btw, it is appreciated if you can release the feature saving code!
2. Is there a little mismatch in Cluster-aided Classifier architecture between Fig.4 and code implementation [here](https://github.com/silicx/DLSA/blob/9559ab64a2eb331ea5b20a89a87ba81b83147d40/models/Classifiers.py#L60)?

Looking forward to your reply.

**Comment by silicx** [comment]
Hi, Zhengzhuo!
1. **Only** PaCo features are extracted with augmentation that identical to the original paco code and we are going to provide the extracted feature.
2. Our code of CAC is equivalent to that in paper since we use **linear** classifier (linear transformation after concatenation equals to addition after linear transformation, i.e. W_1x+W_2y = W_3[x y]). Of course the code should be amended if you work on non-linear classifiers.
Thanks for your attention!

**Comment by XuZhengzhuo** [comment]
Thx for your response! Wouldn't it be better to show a structure illustration of saving 'feature_xxx.h5' in the README?
